# Generated by Django 5.2.11 on 2026-06-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Used for the URL (e.g. fitness-tips-for-2026)', unique=True)),
                ('author', models.CharField(default='FitZone Team', max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blog/')),
                ('category', models.CharField(choices=[('Fitness', 'Fitness'), ('Nutrition', 'Nutrition'), ('Workout', 'Workout'), ('Health', 'Health')], default='Fitness', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
