# Generated by Django 5.2.11 on 2026-06-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog',
            field=models.ImageField(blank=True, help_text='Thumbnail Image', null=True, upload_to='blog/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video',
            field=models.FileField(blank=True, help_text='Optional: Upload an MP4 video', null=True, upload_to='blog_videos/'),
        ),
    ]
